name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ros_monitor_ci -f .devcontainer/Dockerfile .

      - name: Run ruff check in Docker container
        run: |
          docker run --rm \
            -e PYTHONPATH=/ros_monitor:/opt/ros/jazzy/lib/python3.12/site-packages:/venv/lib/python3.12/site-packages \
            -v ${{ github.workspace }}:/ros_monitor \
            ros_monitor_ci \
            /venv/bin/ruff check .

      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -e PYTHONPATH=/ros_monitor:/opt/ros/jazzy/lib/python3.12/site-packages:/venv/lib/python3.12/site-packages \
            -v ${{ github.workspace }}:/ros_monitor \
            ros_monitor_ci \
            /venv/bin/python3 -m pytest
